import "dotenv/config";
import mongoose from "mongoose";
import bcrypt from "bcryptjs";
import { connectDB } from "./config/db.js";
import { MONGO_URI } from "./config/appConfig.js"
import User from "./models/User.js";
import Channel from "./models/Channel.js";
import Video from "./models/Video.js";

(async ()=>{
  await connectDB(MONGO_URI);
  await Promise.all([User.deleteMany({}), Channel.deleteMany({}), Video.deleteMany({})]);

  const pass = await bcrypt.hash("password123", 10);
  const user = await User.create({ username:"JohnDoe", email:"john@example.com", password:pass });
  const channel = await Channel.create({ channelName:"Code with John", owner:user._id, description:"Coding tutorials", channelBanner:"" });

  const videos = await Video.insertMany([
  {
    title: "Peony Flower Blooming (Time-lapse)",
    description: "Beautiful time-lapse of a peony flower blooming.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b4/Time_lapse_of_Peony_flower_blooming.webm/Time_lapse_of_Peony_flower_blooming.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Time_lapse_of_Peony_flower_blooming.webm/320px--Time_lapse_of_Peony_flower_blooming.webm.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Nature",
    views: 8200,
  },
  {
    title: "Yellow Flowers (AV1 Sample)",
    description: "Sample video of yellow flowers encoded as an AV1 test.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/2a/Yellow_flowers_%28AV1_sample%29.webm/Yellow_flowers_%28AV1_sample%29.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Yellow_insects_on_yellow_marigold.jpg/640px-Yellow_insects_on_yellow_marigold.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Nature",
    views: 6500,
  },
  {
    title: "Lalbagh Flower Show 2024 – Independence Day",
    description: "Scenes from the 216th flower show at Lalbagh, Bengaluru, on Indian Independence Day.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c0/Indian_Independence_day_celebration_216th_flower_show_2024%2C_Lalbagh%2C_Bangalore_01.ogg/Indian_Independence_day_celebration_216th_flower_show_2024%2C_Lalbagh%2C_Bangalore_01.ogg.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Part_of_the_Dibleys_Streptocarpus_display_at_the_Chelsea_Flower_Show_in_May_2011.JPG/640px-Part_of_the_Dibleys_Streptocarpus_display_at_the_Chelsea_Flower_Show_in_May_2011.JPG",
    channel: channel._id,
    uploader: user._id,
    category: "News",
    views: 9700,
  },
  {
    title: "Muskoxen Floral Sculpture – Mosaïcanada 2017",
    description: "A floral installation of muskoxen at Mosaïcanada 2017.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/fe/The_Muskoxen_made_with_flower%2C_Mosa%C3%AFcanada_2017.webm/The_Muskoxen_made_with_flower%2C_Mosa%C3%AFcanada_2017.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Flower_sculpture_in_Park_%C5%9Al%C4%85ski%2C_July_2021.jpg/640px-Flower_sculpture_in_Park_%C5%9Al%C4%85ski%2C_July_2021.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Science",
    views: 7300,
  },
  {
    title: "Flower Parade Highlights – Rijnsburg 2013",
    description: "Highlights from the 2013 flower parade in Rijnsburg, Holland.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/3/3f/Flower_Parade_Highlights_from_Holland_-_Rijnsburg_2013.webm/Flower_Parade_Highlights_from_Holland_-_Rijnsburg_2013.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Bloemencorso_Zundert_2023_-_Gouden_Regen_2.jpg/640px-Bloemencorso_Zundert_2023_-_Gouden_Regen_2.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Comedy",
    views: 5600,
  },
  {
    title: "Joy & Heron – Animated Short",
    description: "A charming animated story about kindness between a dog and a heron.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1c/Joy_%26_Heron_-_Animated_CGI_Spot_by_Passion_Pictures.webm/Joy_%26_Heron_-_Animated_CGI_Spot_by_Passion_Pictures.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Big.Buck.Bunny.-.Frank.Rinky.Gimera.png/640px-Big.Buck.Bunny.-.Frank.Rinky.Gimera.png",
    channel: channel._id,
    uploader: user._id,
    category: "Comedy",
    views: 10100,
  },
  {
    title: "Snowball Fight (Scratch Animation)",
    description: "Stick-figure snowball fight animated frame-by-frame in Scratch.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/4e/Snowball_Fight.webm/Snowball_Fight.webm.360p.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Snowball_fight_at_China.jpg/640px-Snowball_fight_at_China.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Animation",
    views: 4800,
  },
  {
    title: "Lamput – Music Moments 4",
    description: "Lamput gets a musical power-up—Cartoon Network India short.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/ff/Lamput_-_Music_Moments_4_-_Lamput_Cartoon_-_Cartoon_Network_India.webm/Lamput_-_Music_Moments_4_-_Lamput_Cartoon_-_Cartoon_Network_India.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Quimi13.png/640px-Quimi13.png",
    channel: channel._id,
    uploader: user._id,
    category: "Music",
    views: 6900,
  },
  {
    title: "Skype Animation Test (Stop-motion)",
    description: "Clay/stop-motion character test created for Skype.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b8/Skype_Animation_Test.webm/Skype_Animation_Test.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/%D0%A1%D1%83%D0%BD%D0%B4%D1%83%D0%BA_%282000%29.jpg/640px-%D0%A1%D1%83%D0%BD%D0%B4%D1%83%D0%BA_%282000%29.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Games",
    views: 5400,
  },
  {
    title: "Kiron – Higher Education for Refugees",
    description: "Explainer on Kiron’s mission to provide higher education access to refugees.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/f/f8/Kiron_Open_Higher_Education_for_Refugees_explained_by_simpleshow_foundation.webm/Kiron_Open_Higher_Education_for_Refugees_explained_by_simpleshow_foundation.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Students_on_masks.jpg/640px-Students_on_masks.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Education",
    views: 6200,
  },
  {
    title: "MOOC: A scuola con Wikipedia (Unit 1.3)",
    description: "Italian MOOC unit: ‘A scuola con Wikipedia’.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/2d/1.3_Pilastro_2_MOOC_A_scuola_con_Wikipedia.webm/1.3_Pilastro_2_MOOC_A_scuola_con_Wikipedia.webm.480p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Wiki_Education_attends_Dr._Amin_Azzam%27s_spring_2018_UCSF_class_24.jpg/640px-Wiki_Education_attends_Dr._Amin_Azzam%27s_spring_2018_UCSF_class_24.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Education",
    views: 4300,
  },
  {
    title: "Mini Metro – Game Over Previs",
    description: "Concept previs for the ‘game over’ transition in Mini Metro.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/3/37/Mini_Metro_game_over_previs.webm/Mini_Metro_game_over_previs.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Chaos_War_game_screenshot.png/640px-Chaos_War_game_screenshot.png",
    channel: channel._id,
    uploader: user._id,
    category: "Sports",
    views: 5100,
  },
  {
    title: "bob’s game – Outside Test (2013 Demo 3)",
    description: "Walkthrough of the outside map in the 2013 demo of bob’s game.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/24/Bob%27s_game_Outside_test.webm/Bob%27s_game_Outside_test.webm.480p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Temporal_game_screenshot.png/640px-Temporal_game_screenshot.png",
    channel: channel._id,
    uploader: user._id,
    category: "Sports",
    views: 3800,
  },
  {
    title: "4Fourths – Game Trailer (HD)",
    description: "Trailer for the indie game 4Fourths.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/a/ab/4Fourths_game_trailer_HD.webm/4Fourths_game_trailer_HD.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Cave_Troll_Level_Of_Sintel_The_Game.png/640px-Cave_Troll_Level_Of_Sintel_The_Game.png",
    channel: channel._id,
    uploader: user._id,
    category: "Games",
    views: 4400,
  },
  {
    title: "Farewell North – Official Trailer",
    description: "Explore islands as a collie in this emotional open-world adventure.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/5/53/Farewell_North_-_Official_Game_Trailer.webm/Farewell_North_-_Official_Game_Trailer.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Karate_oric_game04.jpg/640px-Karate_oric_game04.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Games",
    views: 7700,
  },
  {
    title: "MalaMala Game Reserve (South Africa)",
    description: "Wildlife and landscapes from the MalaMala Game Reserve.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/8/84/MalaMala_Game_Reserve%2C_South_Africa.webm/MalaMala_Game_Reserve%2C_South_Africa.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/IncredipedeScreenshot35.jpg/640px-IncredipedeScreenshot35.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Nature",
    views: 6900,
  },
  {
    title: "Ihsaniye Dam (Kocaeli)",
    description: "Scenic footage near Ihsaniye Dam, Karamürsel – Kocaeli.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/13/Ihsaine_baraji.webm/Ihsaine_baraji.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/2014_Scar_House_Reservoir_Dam.jpg/640px-2014_Scar_House_Reservoir_Dam.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Travel",
    views: 3500,
  },
  {
    title: "Pen Dinas, Aberystwyth – Local Nature Reserve",
    description: "Views of Pen Dinas in Aberystwyth, Wales.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/42/Bryngaer_Pen_Dinas%2C_Aberystwyth%2C_Cymru_%28Wales%29_Local_Nature_Reserve.webm/Bryngaer_Pen_Dinas%2C_Aberystwyth%2C_Cymru_%28Wales%29_Local_Nature_Reserve.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Attenborough_Nature_Reserve_-_geograph.org.uk_-_5385550.jpg/640px-Attenborough_Nature_Reserve_-_geograph.org.uk_-_5385550.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Travel",
    views: 4200,
  },
  {
    title: "Nizhnehopersky Nature Park",
    description: "Footage from the Nizhnehopersky Nature Park, Volgograd Oblast.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/d/d8/Nizhnehopersky_Nature_Park_109.webm/Nizhnehopersky_Nature_Park_109.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Brockholes_Nature_Reserve_-_geograph.org.uk_-_4544679.jpg/640px-Brockholes_Nature_Reserve_-_geograph.org.uk_-_4544679.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Nature",
    views: 3600,
  },
  {
    title: "Yazavni–Ozertsia Nature Reserve (Velyka Blyzna)",
    description: "Hydrological reserve in Volyn Oblast, featuring Lake Velyka Blyzna.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c3/Yazavni_Kovelskyi_Volynska-Ozertsia_nature_reserve-Velyka_Blyzna.webm/Yazavni_Kovelskyi_Volynska-Ozertsia_nature_reserve-Velyka_Blyzna.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Mersehead_Nature_Reserve_-_geograph.org.uk_-_2994815.jpg/640px-Mersehead_Nature_Reserve_-_geograph.org.uk_-_2994815.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "News",
    views: 3400,
  },
  {
    title: "Tbilisi Life – EOS M3 (Creative Commons)",
    description: "Street scenes from Tbilisi filmed on a Canon EOS M3.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/3/36/Tbilisi_life_-_Georgia_Travel_-_canon_camera_Eosm3_-_Creative_commons.ogv/Tbilisi_life_-_Georgia_Travel_-_canon_camera_Eosm3_-_Creative_commons.ogv.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Roadside_Nature_Reserve_-_geograph.org.uk_-_415429.jpg/640px-Roadside_Nature_Reserve_-_geograph.org.uk_-_415429.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Travel",
    views: 6000,
  },
  {
    title: "Tbilisi Life – EOS M17 (Creative Commons)",
    description: "Tbilisi city footage shot on Canon EOS M17.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c8/Tbilisi_life_-_Georgia_Travel_-_canon_camera_Eosm17_-_Creative_commons.ogv/Tbilisi_life_-_Georgia_Travel_-_canon_camera_Eosm17_-_Creative_commons.ogv.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Brockholes_Nature_Reserve_%28geograph_2088041%29.jpg/640px-Brockholes_Nature_Reserve_%28geograph_2088041%29.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Travel",
    views: 5200,
  },
  {
    title: "Visions of the Future – Air Travel (Part 6/6)",
    description: "Futuristic concepts and ideas for air travel.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a5/VISIONS_OF_THE_FUTURE_AIR_TRAVEL_part_6-6_4K.webm/VISIONS_OF_THE_FUTURE_AIR_TRAVEL_part_6-6_4K.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Airplane_of_the_future.jpg/640px-Airplane_of_the_future.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Tech",
    views: 8800,
  },
  {
    title: "Tbilisi Life – EOS M6 (Creative Commons)",
    description: "Georgia travel footage shot on a Canon EOS M6.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/28/Tbilisi_life_-_Georgia_Travel_-_canon_camera_Eosm6_-_Creative_commons.ogv/Tbilisi_life_-_Georgia_Travel_-_canon_camera_Eosm6_-_Creative_commons.ogv.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Merak_tarung.jpg/640px-Merak_tarung.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Travel",
    views: 5700,
  },
  {
    title: "Warrington’s Victorian Carousel",
    description: "Historic carousel ride in Warrington.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/7/7b/Warringtons_Victorian_Carousel.ogv/Warringtons_Victorian_Carousel.ogv.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ride_on_the_South_Bank%2C_London_SE1_-_geograph.org.uk_-_5206611.jpg/640px-Ride_on_the_South_Bank%2C_London_SE1_-_geograph.org.uk_-_5206611.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Culture",
    views: 4100,
  },
  {
    title: "Furcifer Pardalis – Moving Eyes",
    description: "A panther chameleon (Furcifer pardalis) moving its eyes independently.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/90/Furcifer_pardalis_moving_eyes.ogv/Furcifer_pardalis_moving_eyes.ogv.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Benny_Trapp_Anatololacerta_oertzeni_Rhodos.jpg/640px-Benny_Trapp_Anatololacerta_oertzeni_Rhodos.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Wildlife",
    views: 6400,
  },
  {
    title: "Papilio Glaucus – Male Puddling",
    description: "Eastern tiger swallowtail butterfly engaging in puddling behavior.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/cf/Papilio_glaucus-male_puddling.webm/Papilio_glaucus-male_puddling.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Bengal_tiger_%28Panthera_tigris_tigris%29_female_3.jpg/640px-Bengal_tiger_%28Panthera_tigris_tigris%29_female_3.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Travel",
    views: 4600,
  },
  {
    title: "Wuppertal Zoo – Amur Tiger",
    description: "Amur tiger (Panthera tigris altaica) at Wuppertal Zoo.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/62/Wuppertal_-_Zoo_-_Panthera_tigris_altaica_01_%280%29_ies.webm/Wuppertal_-_Zoo_-_Panthera_tigris_altaica_01_%280%29_ies.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Tiger-2.jpg/640px-Tiger-2.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "News",
    views: 7100,
  },
  {
    title: "Giraffe Eating Leaves",
    description: "A giraffe feeding on leaves from a tall tree.",
    videoUrl: "https://upload.wikimedia.org/wikipedia/commons/transcoded/8/85/Giraffe_eating_leaves.webm/Giraffe_eating_leaves.webm.720p.vp9.webm",
    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/042_Masai_giraffe_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg/640px-042_Masai_giraffe_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
    channel: channel._id,
    uploader: user._id,
    category: "Science",
    views: 5800,
  }
]);

  console.log("✅ Seeded:", { user:user.username, channel:channel.channelName, videos:videos.length });
  await mongoose.disconnect();
  process.exit(0);
})();
